
# 權利客體―以「物」為中心

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

## 權力的基本概念
<table>
  <tr>
    <th>權利</th>
    <th>權利主體</th>
    <th>權利客體</th>
  </tr>
  <tr>
    <td>享受特定利益的力量</td>
    <td>得享有權利者<br>
       （擁有權利能力者)</td>
    <td>權利支配的對象</td>
  </tr>
</table>

## 物權的基本原則：一物一權

- 一個物權支配一個特定的物

  例：書包中的民法總則，刑法總則與小六法共有三個所有權

- 物權抽象，物是具體的

  不代表無體物不是物

- 以法律行為使權力發生變動時，是物權改變

  例：買一隻羊，不是羊此物發生改變，是的物權改變

\pagebreak

## 物的判斷：

### 1.不以有體物為限，亦可為無體物
<table>
  <tr>
    <th width="50%">有體物</th>
    <th width="50%">無體物</th>
  </tr>
  <tr>
    <td>外觀上具備一定之形體</td>
    <td>沒有一定之形體</td>
  </tr>
  <tr>
    <td>車子、房屋、羊</td>
    <td>氣體、液體、電力</td>
  </tr>
</table>

### 特例討論：電子檔案是否為物？

- 正方：從權利主體的保護利義論

將其納入物的範圍，使其能成為侵權行為之客體。例如將他人之電子檔案以木馬病毒摧毀。

- 反方：比照德國法，採有體物之觀念

電子檔案僅屬於精神之產物(類無體財產權)，但其交易仍可依435條準用物之買賣或租賃之規定


### 2.可受人類支配

- 特指具排他性的支配，物權得直接支配標的物

  + 支配：是指依權利人之意思，對物管領處分。<br>例外：愛情、時間、資訊不能被支配。

  + 直接:支配標的物時，他人之意思或行為不能介入。
  <br>例外資訊、知識等不能防止獲取。(但仍可以無體財產權的形式保護)。

### 3.非人格性

- 因人為權利主體，人之身體乃人格權的一部分

- 但離開身體之器官、頭髮等依然可以為物

  + 其為不通融物，即不可交易買賣(民72)
  
  + 僅得在一定條件下贈與(人體器官移植條例6)

\pagebreak

### 骨灰、屍體使否為物

- 屍體：多數學說認為屍體為物，構成遺產，應為繼承人所公同共有， 其所有權內涵與其他財產權之所有權不同，應以屍體之埋葬、管理、祭祀及供養為目的，不得自由使用、收益及處分，拋棄繼承之效力不及於此。

- 骨灰：與屍體類型相似，使用統一解釋

- 身體之人工部分：恢復最原始物之狀態，其是否分離因由繼承者決定，由繼承者獲得處分權

- 木乃伊或骷髏：得為權利客體

[臺灣桃園地方法院92年度國字第4號判決]("https://tyd.judicial.gov.tw")

> 骨灰是否為物，法無明文，惟參酌多數學說認為屍體為物，構成遺產，應為繼承人所公同共有， 其所有權內涵與其他財產權之所有權不同，應以屍體之埋葬、管理、祭祀及供養為目的，不得自由 使用、收益及處分，本院認骨灰性質與屍體相近，應作同一解釋較符法理及我國社會上一般觀念。 故被告抗辯本件原告主張寄放於納骨塔之骨灰應屬原告及其他繼承人所繼承遺產之一部，屬全體繼 承人公同共有乙節，應屬可採。

### 4.存在獨立性

- 必須存在一定之空間、範圍<br>
  <i class="material-icons" style="font-size:13px">clear</i>
  流動的河流，空中的閃電<br>
   <i class="material-icons" style="font-size:13px">check</i>
   經過登記後的不動產

- 必須獨立個必存在，數物之重要成份而不得分離者，不得作為物權之客體，即一物一權<br>
  <i class="material-icons">clear</i>
  土地上之樹木之果實(但得作為買賣之標的)
  
### 5.可滿足人類生活所需

- 必須對人類生活有特殊意義或功能<br>
  <i class="material-icons" style="font-size:13px">clear</i>
  一粒米、湖裡之微生物<br>
   <i class="material-icons" style="font-size:13px">check</i>
   雕刻過的米、專供研究而培養成的微生物

\pagebreak

## 物的種類{-}

## 動產與不動產

### 區別標準

[民66：不動產](https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=B0000001&flno=66)

> 1.稱不動產者，謂土地及其定著物。<br>
  2.不動產之出產物，尚未分離者，為該不動產之部分。
 
- 定著物定義：最高法院63年第六次民庭庭推總會議決議(一)

> 民法第六十六條第一項所謂定著物，係指(1)非土地之構成部分，(2)繼續附著於土地，而(3)達一定經濟上目的，(4)不易移動其所在之物而言。凡屋頂尚未完全完工之房屋，其已足避風雨，可達經濟上使用之目的者，即屬土地之定著物，買受此種房屋之人，乃係基於法律行為，自須辦理移轉登記，始能取得所有權。

- 爛尾樓，違建：皆符合


[釋字93號](https://cons.judicial.gov.tw/docdata.aspx?fid=100&id=310274)

- 輕便軌道：符合

> 輕便軌道除係臨時敷設者外，凡繼續附著於土地而達其一定經濟上之目的者，應認為不動產。
 
[民67：動產](https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=B0000001&flno=67)

> 稱動產者，為前條所稱不動產以外之物。

### 區別實益：<mark>所有權權利變動之方法不同</mark>

[民758：不動產必須要書面登記](https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=B0000001&flno=67)

> 1.不動產物權，依法律行為而取得、設定、喪失及變更者，非經登記，不生效力。<br>
  2.前項行為，應以書面為之。

為何違章建築、爛尾樓難以處理 => 成為未登記之不動產，亦難以轉移，變更

## 主物與從物

第 68 條

>非主物之成分，常助主物之效用，而同屬於一人者，為從物。但交易上有特別習慣者，依其習慣。

本項為任意而非強行規定，當事人得以以特約排除。

### 定義

- 非主物之成分:從物必須為獨立之物;反例：汽車之安全帶，僅屬於獨立之物

- 常助主物之效用:

  + 脫離主物就無經濟效用者;例：鎖與鑰匙、電視機與遙控器
  
  + 必須恆常性而非僅暫時輔助主物使用;反例：餐具、塑膠袋

- 主物與從物同屬於一人:旨在保護物的所有權 

- 須交易上無特別習慣:交易習慣具優先性

此處應談論的是「主物之處分之效力是否即於從物問題」，從物之判斷不會因交易習慣而改變

例：不論負擔或處分行為，即使手機與手機殼具有有主從性質，手機之處分均不影響手機殼，非因交易習慣否認手機殼為從物，僅是「處分」不及於從物。

### 區別實益

1.主物之「處分」，及於從物 

通說認為此處應包含債權與物權行為

- 於負擔行為(債權行為)應可贊同，例如契約雖未就是否賣出從物約定，但依主物之效力及於從物，其移轉之標的物應包含從物

- 於所有權之轉移處分則有待商榷。

  + 不動產：
  除法律有特別規定之外，主物與從物必需分別登記(物權變動行為)
  例：作為從物之獨立車庫，其所有權必須完成獨立移轉受讓人使獲取所以權。
  
  + 動產：
  主物設定動產質權者，其效力不一定及於從物
  動產通常需移轉佔有，使生物權變動效力，若從物未交付，質權之效力應不及於此。
  
2.契約解除(民§362)

買賣之契約包含從物與主物，因主物有瑕疵解除契約，效力及於從物。

但若從物有瑕疵，僅得就從物之部分加以解除。

>因主物有瑕疵而解除契約者，其效力及於從物。<br>
從物有瑕疵者，買受人僅得就從物之部分為解除。


##  天然孳息、法定孳息

### 民§69

> I：稱天然孳息者，謂果實、動物之產物及其他依物之用法所收穫之出產物。<br>
II：稱法定孳息者，謂利息、租金及其他因法律關係所得之收益。

物之用法：並非限定於特定用法，例：非以生產牛乳之水牛，其牛奶不失為天然孳息

與主物有別：不得為物之本體一部分;例：水牛之牛肉

### 天然孳息之歸屬

1.原物主義與收取權人

民§766(所有人收益權)，原則上不問何人生產，論原物之所有人

> 物之成分及其天然孳息，於分離後，除法律另有規定外，仍屬於其物之所有人。

民§70，但若有收取權人，天然孳息應屬於收取權人

> 有收取天然孳息權利之人，其權利存續期間內，取得與原物分離之孳息。

例：承租人(地上權人)在土地上種植果樹，在果實分離前，果實之所有權仍屬於出租人(民§66I)。<br>
若果實與果樹分離，且在承租期間(權利存續時間)，果實屬於承租人(民§70)。<br>
若非於承租期間，果實屬於承租人(民§776)<br>

2.鄰地所有人：民§798

若天然孳息落於臨人之土地，其物權應屬於鄰人。但若臨地為公有地者，仍屬於土地權人。

> 果實自落於鄰地者，視為屬於鄰地所有人。但鄰地為公用地者，不在此限。

3.善意占有人

只要為善意之佔有，僅管其在該土地上收取，亦不負有返還之義務

民§§952、943

> 952：善意占有人於推定其為適法所有之權利範圍內，得為占有物之使用、收益。<br>
943:占有人於占有物上行使之權利，推定其適法有此權利。