# 要約與承諾

- 法律行為？事實行為？



契約之成立，透過雙方之意思表示合致，而與欲締約者之意思表示稱**要約**，反之，相對他人所為之意思表示則為**承諾**，契約即為兩者合致之**法律行為**。

另當注意，要約或承諾本質均非單獨行為，無民法§78條之適用(限制行為能力人未得法定代理人之允許，所為之單獨行為，無效。)，而透過兩者合致後，依79條之規定，得法定代理人承認後始生效力。

## 要約

所謂要約，即ㄧ締約者欲喚起相對人對自己為承諾之意思表示。而ㄧ要約有不可欠缺**必要之點**，與不必要之點，如常素與偶素之區別。

### 要約之必要點

在有名契約中，立法者已在內文中明定必要之點，如民法第345條第1項之規定：「稱買賣者，謂當事人約定一方移轉財產權於他方，他方支付價金之契約。」當賣方與買方就所移轉之標的物語價金互相同意，則交易成立。因此，買賣標的物與價金為必要之點。

又如租賃契約(民法§421-I)，必須具備租賃物之使用與租金。僱傭契約(民法§482)則為勞務內容與報酬。

### 常素與偶素

所謂常素，是指**常態性存在契約之內容**，因此無需特別明定，即包含在契約內。但當事人可依自己之意思，特別約定將已排除，例如買賣契約中出賣人之瑕疵擔保責任(§354)

而偶素則為某種法律事實，若未特別規定，則不成為契約之一部分，如法律行為附條件及期限等。

當雙方對非必要之點有所爭議，而未以特別約定時，法院應依其事件之性質定之(§153 II)

### 要約之引誘

要約之引誘，乃ㄧ種**意思通知**，應與要約有所區別，如叫賣。

表意人之表示，若具備所有必要之點，應視其是否**ˋ注重當事人特性**，如徵才廣告、租屋訊息，表意人保留決定締約之權利，若欲與締約者，應向該廣告主提出要約。

民法第154條第2項規定：「貨物標定賣架陳列者，視為要約。但價目表之寄送，不是為要約。」蓋價目表之寄送、不特定發送之廣告單可視為要約。但消保法規定，廣告主不得以廣告只是要約之引誘而不負內容之保證。另外，依其要約之性質，有實務認為，網站標定價格錯誤時，可不承認契約成立。

當直接將實體物交由相對人，則為現物要約，相對人承諾無需負通知義務，契約可成立。若未經消費者要約而直接郵遞或投遞，消費者既不負保管義務，亦不得視其沈默為承諾。消費者定相當期限通知取回而逾期未取回，或無法通知者，視為拋棄。若未經通知，而超過1個月，仍不取回者，同視為拋棄。消費者得請求返回寄送物所受之損害，及處理寄送物所支出之必要費用。

### 要約生效與撤銷

要約與承諾皆適用總則篇之規定。以對話意思表示者，以相對了解時發生效力(§94)。非對話意思表示者，以**通知達到相對人時**發生效力(§94)。

要約人可在效力發生前，撤回要約，而該撤回要約必須**同時或先時抵達**(§95 I但)。而撤回之方式無所限制。

若要約之撤回未先於要約，**而相對人可得知者，須發遲到之通知，怠於通知者，視為未遲到**(§162)。如要約人在上午寄出要約，中午時後悔，以急件方式送出撤回之要約，然因郵差之失誤，將該急件視為一般信件，導致撤回未先於要約，相對人應發出撤回遲到之通知，而相對人怠於通知者，要約之撤回有其效力。


### 要約拘束力

當要約生效時，依民法第154條第ㄧ項，要約人即授其拘束，不得**擴張、限制、變更或撤銷**，此稱為**形式效力**。

而效力發生後，行為人獲得**承諾資格**，而不負**承諾義務**，此為**實質效力**。欠缺實質效力者，不得主張契約成立。此資格乃**純或法律上之利益**(§77但)，對限制行為能力人而言，無需達到其法定代理人同意始發生效力


若要約人以明文方式不受拘束，或依其情形或事件之性質可認**當事人無受拘束之意思者**，可排除要約拘束力(§154 I但)。不受拘束，有認為乃形式上，**保留撤回權**。亦有認為，因是實質上可完全拘束限制，可**保留締約權限與內容修改**。

有疑問者，若可任意修改內容，應為要約之引誘而非要約，再觀其文義與規範目的，應採形式上拘束立可排除較為妥當。但仍應以契約自由作為最大前題。

>民法§154：<br>
I：契約之要約人，因要約而受拘束。但要約當時預先聲明不受拘束，或依其情形或事件之性質，可認當事人無受其拘束之意思者，不在此限。<br>
II：貨物標定賣價陳列者，視為要約。但價目表之寄送，不視為要約。

### 要約消滅

既然有拘束力，那就勢必有消散的一天

1.要約經拒絕

當相對人拒絕對要約做出承諾，要約即失去拘束力(§155)

要約之拒絕為單方意思表示，可為任何形式、明示或默示。若為默示，除法律有特別規定(§387I)，通常視為拒絕之意思(§386)。


2.要約未定有承諾期限

若一要約未規定有承諾期限，**非立時要約，則失去其拘束力**(§156)。

所謂**立時**，並非刻不容緩(行為人必須在聽完要約即作出承諾)，而是**相對人足以充分了解要約內容**，並且當以不同實際情況判斷。如雙方在餐廳討論締約，相對人對於要約未再聽完承諾，但在上完廁所，吃完蛋糕後答應，仍為立時承諾。

若為**非對話之為定期限要約**，則依**通常情形可期待諾到達之時期，而相對人不為承諾時，失去效力**(§157)。通常期限應包含**3個**期間，包含**要約達到相對人之時期**、**相對人之考慮期間**、**承諾達到要約人之時間**。

3.法律特別規定

拍賣，各應買人皆有知道其他人之條件與再次出價之權利

標賣，應買人不知其他人之條件，並且無再提出之機會

據此，拍賣之應買人之出價動作應為要約，拍賣人敲槌同意為承諾。

而標賣，法雖未明文規定究竟為要約引誘或要約，但若**明定出價最高之投標者訂約**，則該規定視為要約，而投標最高者視為**承諾**，買賣契約成立，標賣人須負出賣人之義務。

4.相對人死亡或喪失行為能力

要約之發出若具特定之相對人，而該行為人死亡，則該要約自應消失。然若要約人死亡，除了**有反對之意思表示**、**注重當事人性質(委任、僱傭)**要約失其效力，該要約之拘束力轉由該要約之繼承人。

若相對人為**無行為能力人**，要約之意思表示應向其法定代理人為之(§96)，否則不生效力。但若為**發出途中相對人喪失行為能力**，其要約**不失其效力**(§95II)。


## 承諾

承諾，為對要約之同意之意思表示，既可為對話或非對話之方式，對話表示者，以**相對人(要約人)了解時發生效力**(§94)，非對話者，**通知達到相對人發生效力**(§95 I)。

### 承諾之遲到

上述所言，要約在期限結束前未受承諾，失其拘束力。該遲到承諾依民法第160條，視作新的要約，原要約人轉換為承諾人。

按其傳達之承諾方法，若該承諾應準時抵達而遲到，其情形為要約人可知者，要約人應**發遲到之通知**(§159 I)，怠於通知者，視為未遲到(159 II)，契約成立。就非對話之意思表示者，**若行為人已完成其所應為之必要行為，即使通知未達到承諾人**，該承諾則視為遲到，轉為要約。

### 要約變更

一般來說，拒絕後的要約即失去其效力，但若相對人對要約提出變更(限制、擴張、修改)，視為拒絕而為**新要約**(160II)。

例：甲願將其車以100萬於乙，並發出要約。乙不滿其價格，而提出以90萬購買，該意思表示非承諾，而屬於新要約。

### 撤回承諾

承諾之撤回，應準用要約之規定(§163)。必須與承諾之意思表示早於或同時或提前抵達。若應同時抵達而未同時抵達，而要約人可得知者，應發出通知，怠於發出通知而未發出通知者，視為未遲到。

## 交錯要約

所謂交錯要約，即雙方具備相通之合意，而同時發出要約。如股票集保市場中，買方與賣方同時就相同之標的物與價金發出要約。通說認為既然雙方皆有契約達成之合意，契約成立應無損雙方利益，契約之成立時點則以最後之要約到達時點為主。

## 意思實現

民法第161條規定：「依習慣或依其事件之性質，承諾無須通知者，在相當時期內，有可認為承諾之事實時，其契約為成立。前項規定，於要約人要約當時預先聲明承諾無須通知者準用之。」

以**所為之行為係有可認為承諾之事實**為承諾，而不需到達要約人。此類契約成立方式，通常相對人具有相當利益。如具急迫性之水、電、瓦斯之民生用品、或出賣人對商品之保固表示。

### 情形

- 依習慣，承諾無通知：訂位、依照價目表購買商品

- 依事件性質，承諾無通知：如現物要約，自動販賣機

- 要約人預先聲明承諾無通知：如買家在購買前，已明示不需通知，立即出貨

### 客觀承諾之事實

- 履行行為：相對人屢行其義務，如收到急件的賣家寄出商品、或為履行契約做的準備，如餐廳為訂位的食客保留座位

- 受領行為：相對人行使其權利，如拆開現物要約之包裹

### 主觀承諾之事實？

例：A雜誌社以現物要約的形式將雜誌寄給甲，甲誤以為雜誌是兒子所購，拆封閱讀，請問甲與A之間是否成立契約？

依意思實現的概念，雜誌寄送是現物要約，甲在期限內，其拆封閱讀受權利的行為，屬客觀承諾之事實。但，甲屬誤認雜誌為其兒子所購，**缺乏主觀之承諾意思**。

對於主觀的承諾意思是否為必要，尚有爭議。但要解決問題，應認可在**承諾意思有瑕疵或缺乏承諾意思時，應類推適用民法過意思表示的規定**。如發生錯誤時，依民法88條規定撤銷，上述題例，有認為甲可類推適用88條，撤銷契約意思表示，也有認為甲之行為根本沒有承諾意思，因此不成立契約。

### 例題拆解

台東甲於10月1日打電話訂購ㄧ批瓷器，「以十萬元購入，急件，直接送達」，乙於10月2日將瓷器交丙運送，未料未送達前有人以二十萬出價，乙旋即請丙送回。知此情形之甲得否請求乙履行契約交付瓷器？<br>

甲得向乙請求交付A瓶並移轉所有權

甲以348條1項為請求權基礎，必需討論契約是否成立：
  
&emsp;&emsp;甲打電話屬於要約，而乙寄送瓷器的行為可為承諾，依一般通則，契約成立應依民法第153條，以承諾送達要約人之時始成立。題幹之乙以寄送物品之默示承諾，其達到之時應為甲取得物品之時。惟，依民法第161條，承諾無須通知者，有可認為承諾之事實時，其契約為成立。題幹之甲在電報中以「急件、直接送達」之語，合於161第2項之後段所稱之「要約人要約當時預先聲明承諾無須通」而適用本條。乙寄送瓷器時，應為承諾之事實，縱要約人知悉前，亦不得撤回之。故買賣契約成立。


# 懸賞廣告

通常之廣告，如補習班之傳單、路邊預售屋出賣的廣告、某家餐廳的宣傳手冊，都是上述所說之**要約引誘**。

與之區別者，所謂懸賞廣告，應指：「**以廣告之方式，聲明完成一定行為之人，給予報酬。**。」如物品遺失、獎勵發明、尋人啟事等等，廣告本身為要約，以完成特定行為為承諾。

### 要件

1.廣告聲明

- 必須為**最先完成行為之人**

懸賞廣告是要約完成一特定行為，因此，應以先完成該行為之相對人為契約人。若以「處於一狀態者」給予報酬，其非心賞廣告。

例：若設給予「比賽冠軍」報酬，其非完成一行為而是某一狀態人，而設給予「最先抵達山頂者」，則抵達山頂為承諾，首先抵達者為契約人。

- 基於不特定之人

廣告的聲明，必須**使不特定之多數人得以共見或共聞**。所謂不定之人，仍可有一定之範圍設定。反之，若針對特定之人，自然非此類。

例：以「小明登上富士山頂」給予報酬者，屬**附停止條件之贈與**，或在私密的咖啡廳一對二宣達，也非此類。

- 行為本身就是承諾之意思實現

此處之行為，並**不以法律行為為限**，亦可為事實行為。並且，即使相對人是出於「不知有懸賞」而完成行為，亦可主張**報酬請求權**(§§164IV準用164I)，可認此類為**意思實現**(不必為額外之承諾行為)。

### 效力

先完成行為者享有**報酬請求權**，數人共同或同時分別完成行為時，由行為人共同取得報酬請求權(§164II)。

若完成行為可取得一定權利者(例：著作權、商標權)，其權利屬於行為人，

因完成前條之行為而可取得一定之權利者，其權利屬於行為人。但廣告另有聲明者，不在此限(§164-1)。如發明懸賞，若未特別設定，則該發明人享有該產品之著作權。

### 撤回

依民法165條：「預定報酬之廣告，如於行為完成前撤回時，除廣告人證明行為人不能完成其行為外，對於行為人因該廣告善意所受之損害，應負賠償之責。但以不超過預定報酬額為限。」

撤回屬**單獨行為**，行為人單方面之意思表示，即發生效力。而懸賞廣告之特性，若要約人可任意撤回，則相對人難有保證，因此，要約人之撤回，必須以**同一或更有效之方式**，並且若要約人不能證明行為人不能完成行為，則應負賠償之責。

損害賠償，除












