
# 權利客體―以「物」為中心

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

## 權力的基本概念
<table>
  <tr>
    <th>權利</th>
    <th>權利主體</th>
    <th>權利客體</th>
  </tr>
  <tr>
    <td>享受特定利益的力量</td>
    <td>得享有權利者<br>
       （擁有權利能力者)</td>
    <td>權利支配的對象</td>
  </tr>
</table>

## 物權的基本原則：一物一權

- 一個物權支配一個特定的物

  例：書包中的民法總則，刑法總則與小六法共有三個所有權

- 物權抽象，物是具體的

  不代表無體物不是物

- 以法律行為使權力發生變動時，是物權改變

  例：買一隻羊，不是羊此物發生改變，是的物權改變

\pagebreak

## 物的判斷：

### 1.不以有體物為限，亦可為無體物
<table>
  <tr>
    <th width="50%">有體物</th>
    <th width="50%">無體物</th>
  </tr>
  <tr>
    <td>外觀上具備一定之形體</td>
    <td>沒有一定之形體</td>
  </tr>
  <tr>
    <td>車子、房屋、羊</td>
    <td>氣體、液體、電力</td>
  </tr>
</table>

### 特例討論：電子檔案是否為物？

- 正方：從權利主體的保護利義論

將其納入物的範圍，使其能成為侵權行為之客體。例如將他人之電子檔案以木馬病毒摧毀。

- 反方：比照德國法，採有體物之觀念

電子檔案僅屬於精神之產物(類無體財產權)，但其交易仍可依435條準用物之買賣或租賃之規定


### 2.可受人類支配

- 特指具排他性的支配，物權得直接支配標的物

  + 支配：是指依權利人之意思，對物管領處分。<br>例外：愛情、時間、資訊不能被支配。

  + 直接:支配標的物時，他人之意思或行為不能介入。
  <br>例外資訊、知識等不能防止獲取。(但仍可以無體財產權的形式保護)。

### 3.非人格性

- 因人為權利主體，人之身體乃人格權的一部分

- 但離開身體之器官、頭髮等依然可以為物

  + 其為不通融物，即不可交易買賣(民72)
  
  + 僅得在一定條件下贈與(人體器官移植條例6)

\pagebreak

### 骨灰、屍體使否為物

- 屍體：多數學說認為屍體為物，構成遺產，應為繼承人所公同共有， 其所有權內涵與其他財產權之所有權不同，應以屍體之埋葬、管理、祭祀及供養為目的，不得自由使用、收益及處分，拋棄繼承之效力不及於此。

- 骨灰：與屍體類型相似，使用統一解釋

- 身體之人工部分：恢復最原始物之狀態，其是否分離因由繼承者決定，由繼承者獲得處分權

- 木乃伊或骷髏：得為權利客體

[臺灣桃園地方法院92年度國字第4號判決]("https://tyd.judicial.gov.tw")

> 骨灰是否為物，法無明文，惟參酌多數學說認為屍體為物，構成遺產，應為繼承人所公同共有， 其所有權內涵與其他財產權之所有權不同，應以屍體之埋葬、管理、祭祀及供養為目的，不得自由 使用、收益及處分，本院認骨灰性質與屍體相近，應作同一解釋較符法理及我國社會上一般觀念。 故被告抗辯本件原告主張寄放於納骨塔之骨灰應屬原告及其他繼承人所繼承遺產之一部，屬全體繼 承人公同共有乙節，應屬可採。

### 4.存在獨立性

- 必須存在一定之空間、範圍<br>
  <i class="material-icons" style="font-size:13px">clear</i>
  流動的河流，空中的閃電<br>
   <i class="material-icons" style="font-size:13px">check</i>
   經過登記後的不動產

- 必須獨立個必存在，數物之重要成份而不得分離者，不得作為物權之客體，即一物一權<br>
  <i class="material-icons">clear</i>
  土地上之樹木之果實(但得作為買賣之標的)
  
### 5.可滿足人類生活所需

- 必須對人類生活有特殊意義或功能<br>
  <i class="material-icons" style="font-size:13px">clear</i>
  一粒米、湖裡之微生物<br>
   <i class="material-icons" style="font-size:13px">check</i>
   雕刻過的米、專供研究而培養成的微生物

\pagebreak

## 物的種類
### 1.動產與不動產

### 區別標準

[民66：不動產](https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=B0000001&flno=66)

> 1.稱不動產者，謂土地及其定著物。<br>
  2.不動產之出產物，尚未分離者，為該不動產之部分。
 
- 定著物定義

最高法院63年第六次民庭庭推總會議決議(一)

> 民法第六十六條第一項所謂定著物，係指非土地之構成部分，繼續附著於土地，而達一定經濟上目的，不易移動其所在之物而言。凡屋頂尚未完全完工之房屋，其已足避風雨，可達經濟上使用之目的者，即屬土地之定著物，買受此種房屋之人，乃係基於法律行為，自須辦理移轉登記，始能取得所有權。

- 爛尾樓，違建：皆符合


[釋字93號](https://cons.judicial.gov.tw/docdata.aspx?fid=100&id=310274)

- 輕便軌道：符合

> 輕便軌道除係臨時敷設者外，凡繼續附著於土地而達其一定經濟上之目的者，應認為不動產。
 
[民67：動產](https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=B0000001&flno=67)

> 稱動產者，為前條所稱不動產以外之物。

### 區別實益：<mark>所有權權利變動之方法不同</mark>

[民758：不動產必須要書面登記](https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=B0000001&flno=67)

> 1.不動產物權，依法律行為而取得、設定、喪失及變更者，非經登記，不生效力。<br>
  2.前項行為，應以書面為之。

為何違章建築、爛尾樓難以處理=>成為未登記之不動產，亦難以轉移，變更